import { VoucherDto } from '../voucherConfiguration';

export const sampleVoucher1: VoucherDto = {
  id: 'MYAPP100',
  boxId: '1',
  creationDate: new Date(),
  baseOption: 'onetime',
  type: 'percent',
  redemptionDate: new Date(),
  expiryDate: new Date(),
  tag1: 'tag1',
  tag2: 'tag2',
  tag3: undefined,
  priceCut: undefined,
  percentCut: 10,
  beverageConfiguration: undefined,
  ttl: undefined,
  state: 'valid',
  usedCredit: 0,
};

export const sampleVoucher2: VoucherDto = {
  id: 'MYAPP101',
  boxId: '1',
  creationDate: new Date(),
  baseOption: 'onetime',
  type: 'price',
  redemptionDate: new Date(),
  expiryDate: new Date(),
  tag1: 'tag1',
  tag2: 'tag2',
  tag3: undefined,
  priceCut: undefined,
  percentCut: 10,
  beverageConfiguration: undefined,
  ttl: undefined,
  state: 'redeemed',
  usedCredit: 0,
};

export const sampleVoucher3: VoucherDto = {
  id: 'MYAPP102',
  boxId: '1',
  creationDate: new Date(),
  baseOption: 'onetime',
  type: 'beverage',
  redemptionDate: new Date(),
  expiryDate: new Date(),
  tag1: 'tag1',
  tag2: 'tag2',
  tag3: undefined,
  priceCut: undefined,
  percentCut: 10,
  beverageConfiguration: {
    productId: 301,
    extra: [2211],
    printImage: undefined,
  },
  ttl: undefined,
  state: 'redeemed',
  usedCredit: 0,
};

export const sampleVoucher4: VoucherDto = {
  id: 'MYAPP103',
  boxId: '1',
  creationDate: new Date(),
  baseOption: 'onetime',
  type: 'price',
  redemptionDate: new Date(),
  expiryDate: new Date(),
  priceCut: undefined,
  percentCut: 10,
  beverageConfiguration: undefined,
  ttl: undefined,
  state: 'expired',
  usedCredit: 0,
};

export const sampleVoucher5: VoucherDto = {
  id: 'MYAPP104',
  boxId: '1',
  creationDate: new Date(),
  baseOption: 'onetime',
  type: 'price',
  redemptionDate: new Date(),
  expiryDate: new Date(),
  priceCut: undefined,
  percentCut: 10,
  beverageConfiguration: undefined,
  ttl: undefined,
  state: 'cancelled',
  usedCredit: 0,
};
