import {
  Coffeemachine_SML,
  CupSize,
  ExtraCategory,
  ExtraConfiguration,
  ProductCategory,
  ProductConfiguration,
  Season,
  SizeName,
} from '../product';

export const sampleProductMatrix: {
  extras: Record<string, ExtraConfiguration>;
  beverages: {
    hot: Record<string, ProductConfiguration>;
    ice: Record<string, ProductConfiguration>;
    special: Record<string, ProductConfiguration>;
  };
} = {
  extras: {
    '1': {
      name: 'Bild',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 1,
      isAnalyzed: false,
      isDisabled: false,
      price: 0,
      img: 'MyAppCafe_Icons-47',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 0,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 0,
        syrup3: 0,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.print,
    },
    '211': {
      name: 'extrashot',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 211,
      isAnalyzed: true,
      isDisabled: false,
      price: 40,
      img: 'MyAppCafe_Icons_Extra Shot',
      recipe: {
        bean1: 11,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 0,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 0,
        syrup3: 0,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.strength,
    },
    '212': {
      name: 'extrashot',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 212,
      isAnalyzed: true,
      isDisabled: false,
      price: 40,
      img: 'MyAppCafe_Icons_Extra Shot',
      recipe: {
        bean1: 0,
        bean2: 11,
        powder: 0,
        milk1: 0,
        milk2: 0,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 0,
        syrup3: 0,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.strength,
    },
    '2008': {
      name: 'noMilk',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 2008,
      isAnalyzed: false,
      isDisabled: false,
      price: 0,
      img: 'MyAppCafe_Icons_Milch',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 0,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 0,
        syrup3: 0,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.milk,
    },
    '2009': {
      name: 'noMilk',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 2009,
      isAnalyzed: false,
      isDisabled: false,
      price: 0,
      img: 'MyAppCafe_Icons_Milch',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 0,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 0,
        syrup3: 0,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.milk,
    },
    '2010': {
      name: 'noMilk',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 2010,
      isAnalyzed: false,
      isDisabled: false,
      price: 0,
      img: 'MyAppCafe_Icons_Milch',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 0,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 0,
        syrup3: 0,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.milk,
    },
    '2011': {
      name: 'milk1',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 2011,
      isAnalyzed: true,
      isDisabled: false,
      price: 0,
      img: 'MyAppCafe_Icons_Milch',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 30,
        milk2: 0,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 0,
        syrup3: 0,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.milk,
    },
    '2012': {
      name: 'milk1',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 2012,
      isAnalyzed: true,
      isDisabled: false,
      price: 0,
      img: 'MyAppCafe_Icons_Milch',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 40,
        milk2: 0,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 0,
        syrup3: 0,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.milk,
    },
    '2013': {
      name: 'milk1',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 2013,
      isAnalyzed: true,
      isDisabled: false,
      price: 0,
      img: 'MyAppCafe_Icons_Milch',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 50,
        milk2: 0,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 0,
        syrup3: 0,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.milk,
    },
    '2111': {
      name: 'milk2',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 2111,
      isAnalyzed: true,
      isDisabled: false,
      price: 40,
      img: 'MyAppCafe_Icons_Milch',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 1,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 0,
        syrup3: 0,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.milk,
    },
    '2112': {
      name: 'milk2',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 2112,
      isAnalyzed: true,
      isDisabled: false,
      price: 50,
      img: 'MyAppCafe_Icons_Milch',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 1,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 0,
        syrup3: 0,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.milk,
    },
    '2113': {
      name: 'milk2',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 2113,
      isAnalyzed: true,
      isDisabled: false,
      price: 60,
      img: 'MyAppCafe_Icons_Milch',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 1,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 0,
        syrup3: 0,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.milk,
    },
    '2121': {
      name: 'milk2',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 2121,
      isAnalyzed: true,
      isDisabled: false,
      price: 0,
      img: 'MyAppCafe_Icons_Milch',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 1,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 0,
        syrup3: 0,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.milk,
    },
    '2122': {
      name: 'milk2',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 2122,
      isAnalyzed: true,
      isDisabled: false,
      price: 0,
      img: 'MyAppCafe_Icons_Milch',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 1,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 0,
        syrup3: 0,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.milk,
    },
    '2123': {
      name: 'milk2',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 2123,
      isAnalyzed: true,
      isDisabled: false,
      price: 0,
      img: 'MyAppCafe_Icons_Milch',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 1,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 0,
        syrup3: 0,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.milk,
    },
    '2300': {
      name: 'syrup1',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 2300,
      isAnalyzed: true,
      isDisabled: false,
      price: 50,
      img: 'MyAppCafe_Icons_Flavour',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 0,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 15,
        syrup2: 0,
        syrup3: 0,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.syrup,
    },
    '2301': {
      name: 'syrup1',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 2301,
      isAnalyzed: true,
      isDisabled: false,
      price: 70,
      img: 'MyAppCafe_Icons_Flavour',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 0,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 20,
        syrup2: 0,
        syrup3: 0,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.syrup,
    },
    '2302': {
      name: 'syrup1',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 2302,
      isAnalyzed: true,
      isDisabled: false,
      price: 90,
      img: 'MyAppCafe_Icons_Flavour',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 0,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 25,
        syrup2: 0,
        syrup3: 0,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.syrup,
    },
    '2310': {
      name: 'syrup2',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 2310,
      isAnalyzed: true,
      isDisabled: false,
      price: 50,
      img: 'MyAppCafe_Icons_Flavour',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 0,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 15,
        syrup3: 0,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.syrup,
    },
    '2311': {
      name: 'syrup2',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 2311,
      isAnalyzed: true,
      isDisabled: false,
      price: 70,
      img: 'MyAppCafe_Icons_Flavour',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 0,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 20,
        syrup3: 0,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.syrup,
    },
    '2312': {
      name: 'syrup2',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 2312,
      isAnalyzed: true,
      isDisabled: false,
      price: 90,
      img: 'MyAppCafe_Icons_Flavour',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 0,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 25,
        syrup3: 0,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.syrup,
    },
    '2320': {
      name: 'syrup3',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 2320,
      isAnalyzed: true,
      isDisabled: false,
      price: 50,
      img: 'MyAppCafe_Icons_Flavour',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 0,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 0,
        syrup3: 15,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.syrup,
    },
    '2321': {
      name: 'syrup3',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 2321,
      isAnalyzed: true,
      isDisabled: false,
      price: 70,
      img: 'MyAppCafe_Icons_Flavour',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 0,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 0,
        syrup3: 20,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.syrup,
    },
    '2322': {
      name: 'syrup3',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: false,
      id: 2322,
      isAnalyzed: true,
      isDisabled: false,
      price: 90,
      img: 'MyAppCafe_Icons_Flavour',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 0,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 0,
        syrup3: 25,
        syrup4: 0,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.syrup,
    },
    '2330': {
      name: 'syrup4',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: true,
      id: 2330,
      isAnalyzed: true,
      isDisabled: false,
      price: 50,
      img: 'MyAppCafe_Icons_Flavour',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 0,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 0,
        syrup3: 0,
        syrup4: 15,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.syrup,
    },
    '2331': {
      name: 'syrup4',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: true,
      id: 2331,
      isAnalyzed: true,
      isDisabled: false,
      price: 70,
      img: 'MyAppCafe_Icons_Flavour',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 0,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 0,
        syrup3: 0,
        syrup4: 20,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.syrup,
    },
    '2332': {
      name: 'syrup4',
      season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
      isNamingSeasonal: true,
      id: 2332,
      isAnalyzed: true,
      isDisabled: false,
      price: 90,
      img: 'MyAppCafe_Icons_Flavour',
      recipe: {
        bean1: 0,
        bean2: 0,
        powder: 0,
        milk1: 0,
        milk2: 0,
        sugar: 0,
        lidM: 0,
        lidL: 0,
        cupM: 0,
        cupL: 0,
        cupXL: 0,
        cupXXL: 0,
        syrup1: 0,
        syrup2: 0,
        syrup3: 0,
        syrup4: 25,
        water: 0,
        franchiseTax: 0,
      },
      category: ExtraCategory.syrup,
    },
  },
  beverages: {
    hot: {
      '100': {
        name: 'Espresso doppio',
        sizes: [
          {
            sizeName: SizeName.Short,
            id: 101,
            cupSize: 8,
            price: 290,
            extrashot: [212],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 150,
              bean2: 0,
              powder: 0,
              milk1: 0,
              milk2: 0,
              sugar: 1,
              lidM: 1,
              lidL: 0,
              cupM: 1,
              cupL: 0,
              cupXL: 0,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 70,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: false,
        hasChoco: false,
        hasMilk: false,
        hasExtrashot: true,
        hasSyrup: false,
        hasIce: false,
        a_iBtnNbr: 1,
        img: 'MyAppCafe_Icons_Esrpesso',
        category: ProductCategory.hot,
        baseId: 100,
      },
      '200': {
        name: 'Coffee',
        sizes: [
          {
            sizeName: SizeName.Short,
            id: 201,
            cupSize: CupSize.Small,
            price: 240,
            extrashot: [211],
            milk: [2010, 2011, 2121],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.S,
            recipe: {
              bean1: 0,
              bean2: 148,
              powder: 0,
              milk1: 0,
              milk2: 0,
              sugar: 1,
              lidM: 1,
              lidL: 0,
              cupM: 1,
              cupL: 0,
              cupXL: 0,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 190,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Small,
            id: 202,
            cupSize: 12,
            price: 290,
            extrashot: [211],
            milk: [2010, 2012, 2122],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 0,
              bean2: 185,
              powder: 0,
              milk1: 0,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 1,
              cupXL: 0,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 260,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Regular,
            id: 203,
            cupSize: 16,
            price: 310,
            extrashot: [211],
            milk: [2010, 2013, 2123],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 0,
              bean2: 222,
              powder: 0,
              milk1: 0,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 330,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: false,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: false,
        hasIce: false,
        a_iBtnNbr: 2,
        special_a_iBtnNbr: [
          {
            a_iBtnNbr: 4,
            condition: [2011, 2012, 2013, 2111, 2112, 2113],
          },
        ],
        img: 'MyAppCafe_Icons_Coffee',
        category: ProductCategory.hot,
        baseId: 200,
      },
      '300': {
        name: 'Cappuccino',
        sizes: [
          {
            sizeName: SizeName.Small,
            id: 301,
            cupSize: 12,
            price: 320,
            extrashot: [212],
            milk: [2011, 2111],
            numSyrup: 1,
            syrup: [2300, 2310, 2330],
            a_iSML: Coffeemachine_SML.S,
            recipe: {
              bean1: 120,
              bean2: 0,
              powder: 0,
              milk1: 115,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 1,
              cupXL: 0,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Regular,
            id: 302,
            cupSize: 16,
            price: 350,
            extrashot: [212],
            milk: [2012, 2112],
            numSyrup: 1,
            syrup: [2301, 2311, 2331],
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 150,
              bean2: 0,
              powder: 0,
              milk1: 151,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            id: 303,
            cupSize: 20,
            price: 380,
            extrashot: [212],
            milk: [2013, 2113],
            numSyrup: 1,
            syrup: [2302, 2312, 2332],
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 180,
              bean2: 0,
              powder: 0,
              milk1: 192,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: true,
        hasIce: false,
        a_iBtnNbr: 12,
        img: 'MyAppCafe_Icons_Cappucino',
        category: ProductCategory.hot,
        baseId: 300,
      },
      '400': {
        name: 'Flat White',
        sizes: [
          {
            sizeName: SizeName.Small,
            id: 401,
            cupSize: 12,
            price: 310,
            extrashot: [211],
            milk: [2011, 2111],
            numSyrup: 1,
            syrup: [2300, 2310, 2330],
            a_iSML: Coffeemachine_SML.S,
            recipe: {
              bean1: 0,
              bean2: 165,
              powder: 0,
              milk1: 68,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 1,
              cupXL: 0,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Regular,
            id: 402,
            cupSize: 16,
            price: 340,
            extrashot: [211],
            milk: [2012, 2112],
            numSyrup: 1,
            syrup: [2301, 2311, 2331],
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 0,
              bean2: 180,
              powder: 0,
              milk1: 88,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            id: 403,
            cupSize: 20,
            price: 370,
            extrashot: [211],
            milk: [2013, 2113],
            numSyrup: 1,
            syrup: [2302, 2312, 2332],
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 0,
              bean2: 190,
              powder: 0,
              milk1: 108,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: true,
        hasIce: false,
        a_iBtnNbr: 3,
        img: 'MyAppCafe_Icons_Flat White',
        category: ProductCategory.hot,
        baseId: 400,
      },
      '500': {
        name: 'Chai Latte',
        sizes: [
          {
            sizeName: SizeName.Small,
            builtInExtra: [2320],
            id: 501,
            cupSize: 12,
            price: 330,
            milk: [2011, 2111],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.S,
            recipe: {
              bean1: 0,
              bean2: 0,
              powder: 0,
              milk1: 247,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 1,
              cupXL: 0,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Regular,
            builtInExtra: [2321],
            id: 502,
            cupSize: 16,
            price: 360,
            milk: [2012, 2112],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 0,
              bean2: 0,
              powder: 0,
              milk1: 296,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            builtInExtra: [2322],
            id: 503,
            cupSize: 20,
            price: 390,
            milk: [2013, 2113],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 0,
              bean2: 0,
              powder: 0,
              milk1: 358,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: false,
        hasSyrup: false,
        hasIce: false,
        a_iBtnNbr: 5,
        img: 'MyAppCafe_Icons_Chai Latte',
        category: ProductCategory.hot,
        baseId: 500,
      },
      '600': {
        name: 'Cafe Latte',
        sizes: [
          {
            sizeName: SizeName.Small,
            id: 601,
            cupSize: 12,
            price: 330,
            extrashot: [212],
            milk: [2011, 2111],
            numSyrup: 1,
            syrup: [2300, 2310, 2330],
            a_iSML: Coffeemachine_SML.S,
            recipe: {
              bean1: 120,
              bean2: 0,
              powder: 0,
              milk1: 116,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 1,
              cupXL: 0,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Regular,
            id: 602,
            cupSize: 16,
            price: 360,
            extrashot: [212],
            milk: [2012, 2112],
            numSyrup: 1,
            syrup: [2301, 2311, 2331],
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 150,
              bean2: 0,
              powder: 0,
              milk1: 137,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            id: 603,
            cupSize: 20,
            price: 390,
            extrashot: [212],
            milk: [2013, 2113],
            numSyrup: 1,
            syrup: [2302, 2312, 2332],
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 180,
              bean2: 0,
              powder: 0,
              milk1: 170,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: true,
        hasIce: false,
        a_iBtnNbr: 13,
        img: 'MyAppCafe_Icons_Cafe Latte',
        category: ProductCategory.hot,
        baseId: 600,
      },
      '700': {
        name: 'Caffé Mocha',
        sizes: [
          {
            sizeName: SizeName.Small,
            id: 701,
            cupSize: 12,
            price: 370,
            extrashot: [212],
            milk: [2011, 2111],
            numSyrup: 1,
            syrup: [2300, 2310, 2330],
            a_iSML: Coffeemachine_SML.S,
            recipe: {
              bean1: 80,
              bean2: 0,
              powder: 26,
              milk1: 59,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 1,
              cupXL: 0,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Regular,
            id: 702,
            cupSize: 16,
            price: 400,
            extrashot: [212],
            milk: [2012, 2112],
            numSyrup: 1,
            syrup: [2301, 2311, 2331],
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 100,
              bean2: 0,
              powder: 35,
              milk1: 76,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            id: 703,
            cupSize: 20,
            price: 420,
            extrashot: [212],
            milk: [2013, 2113],
            numSyrup: 1,
            syrup: [2302, 2312, 2332],
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 120,
              bean2: 0,
              powder: 44,
              milk1: 93,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hasChoco: true,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: true,
        hasIce: false,
        a_iBtnNbr: 15,
        img: 'MyAppCafe_Icons_Caffe Mocha',
        category: ProductCategory.hot,
        baseId: 700,
      },
      '800': {
        name: 'Hot Chocolate',
        sizes: [
          {
            sizeName: SizeName.Small,
            id: 801,
            cupSize: 12,
            price: 340,
            milk: [2011, 2111],
            numSyrup: 1,
            syrup: [2300, 2310, 2330],
            a_iSML: Coffeemachine_SML.S,
            recipe: {
              bean1: 0,
              bean2: 0,
              powder: 30,
              milk1: 73,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 1,
              cupXL: 0,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Regular,
            id: 802,
            cupSize: 16,
            price: 370,
            milk: [2012, 2112],
            numSyrup: 1,
            syrup: [2301, 2311, 2331],
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 0,
              bean2: 0,
              powder: 40,
              milk1: 80,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            id: 803,
            cupSize: 20,
            price: 400,
            milk: [2013, 2113],
            numSyrup: 1,
            syrup: [2302, 2312, 2332],
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 0,
              bean2: 0,
              powder: 50,
              milk1: 121,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hasChoco: true,
        hasMilk: true,
        hasExtrashot: false,
        hasSyrup: true,
        hasIce: false,
        a_iBtnNbr: 14,
        img: 'MyAppCafe_Icons_Hot Chocolate',
        category: ProductCategory.hot,
        baseId: 800,
      },
      '900': {
        name: 'Americano',
        sizes: [
          {
            sizeName: SizeName.Short,
            id: 901,
            cupSize: 8,
            price: 250,
            extrashot: [212],
            milk: [2010, 2011, 2121],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.S,
            recipe: {
              bean1: 104,
              bean2: 0,
              powder: 0,
              milk1: 0,
              milk2: 0,
              sugar: 1,
              lidM: 1,
              lidL: 0,
              cupM: 1,
              cupL: 0,
              cupXL: 0,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Small,
            id: 902,
            cupSize: 12,
            price: 290,
            extrashot: [212],
            milk: [2010, 2012, 2122],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 130,
              bean2: 0,
              powder: 0,
              milk1: 0,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 1,
              cupXL: 0,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Regular,
            id: 903,
            cupSize: 16,
            price: 310,
            extrashot: [212],
            milk: [2010, 2013, 2123],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 156,
              bean2: 0,
              powder: 0,
              milk1: 0,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: false,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: false,
        hasIce: false,
        a_iBtnNbr: 11,
        special_a_iBtnNbr: [
          {
            a_iBtnNbr: 12,
            condition: [2011, 2012, 2013, 2111, 2112, 2113],
          },
        ],
        img: 'MyAppCafe_Icons_Americano',
        category: ProductCategory.hot,
        baseId: 900,
      },
    },
    ice: {
      '250': {
        name: 'Iced Coffee',
        sizes: [
          {
            sizeName: SizeName.Regular,
            id: 251,
            cupSize: 16,
            price: 310,
            extrashot: [211],
            milk: [2010, 2011, 2111],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 0,
              bean2: 185,
              powder: 0,
              milk1: 0,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: false,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: false,
        hasIce: true,
        a_iBtnNbr: 23,
        special_a_iBtnNbr: [
          {
            a_iBtnNbr: 33,
            condition: [2011, 2012, 2111, 2112],
          },
        ],
        img: 'MyAppCafe_Icons_Coffee Iced',
        category: ProductCategory.ice,
        baseId: 250,
      },
      '350': {
        name: 'Iced Cappuccino',
        sizes: [
          {
            sizeName: SizeName.Regular,
            id: 351,
            cupSize: 16,
            price: 350,
            extrashot: [212],
            milk: [2011, 2111],
            numSyrup: 1,
            syrup: [2300, 2310, 2330],
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 150,
              bean2: 0,
              powder: 0,
              milk1: 119,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            id: 352,
            cupSize: 20,
            price: 380,
            extrashot: [212],
            milk: [2012, 2112],
            numSyrup: 1,
            syrup: [2301, 2311, 2331],
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 180,
              bean2: 0,
              powder: 0,
              milk1: 152,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: true,
        hasIce: true,
        a_iBtnNbr: 8,
        img: 'MyAppCafe_Icons_Cappucino Iced',
        category: ProductCategory.ice,
        baseId: 350,
      },
      '450': {
        name: 'Iced Flat White',
        sizes: [
          {
            sizeName: SizeName.Regular,
            id: 451,
            cupSize: 16,
            price: 340,
            extrashot: [211],
            milk: [2011, 2111],
            numSyrup: 1,
            syrup: [2300, 2310, 2330],
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 0,
              bean2: 180,
              powder: 0,
              milk1: 84,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            id: 452,
            cupSize: 20,
            price: 370,
            extrashot: [211],
            milk: [2012, 2112],
            numSyrup: 1,
            syrup: [2301, 2311, 2331],
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 0,
              bean2: 190,
              powder: 0,
              milk1: 112,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: true,
        hasIce: true,
        a_iBtnNbr: 7,
        img: 'MyAppCafe_Icons_Flat White Iced',
        category: ProductCategory.ice,
        baseId: 450,
      },
      '550': {
        name: 'Iced Chai Latte',
        sizes: [
          {
            sizeName: SizeName.Regular,
            builtInExtra: [2321],
            id: 551,
            cupSize: 16,
            price: 360,
            milk: [2011, 2111],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 0,
              bean2: 0,
              powder: 0,
              milk1: 215,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            builtInExtra: [2322],
            id: 552,
            cupSize: 20,
            price: 390,
            milk: [2012, 2112],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 0,
              bean2: 0,
              powder: 0,
              milk1: 348,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: false,
        hasSyrup: false,
        hasIce: true,
        a_iBtnNbr: 19,
        img: 'MyAppCafe_Icons_Chai Latte Iced',
        category: ProductCategory.ice,
        baseId: 550,
      },
      '650': {
        name: 'Iced Cafe Latte',
        sizes: [
          {
            sizeName: SizeName.Regular,
            id: 651,
            cupSize: 16,
            price: 360,
            extrashot: [212],
            milk: [2011, 2111],
            numSyrup: 1,
            syrup: [2300, 2310, 2330],
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 150,
              bean2: 0,
              powder: 0,
              milk1: 120,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            id: 652,
            cupSize: 20,
            price: 390,
            extrashot: [212],
            milk: [2012, 2112],
            numSyrup: 1,
            syrup: [2301, 2311, 2331],
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 180,
              bean2: 0,
              powder: 0,
              milk1: 150,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: true,
        hasIce: true,
        a_iBtnNbr: 17,
        img: 'MyAppCafe_Icons_Cafe Latte Iced',
        category: ProductCategory.ice,
        baseId: 650,
      },
      '750': {
        name: 'Iced Caffé Mocha',
        sizes: [
          {
            sizeName: SizeName.Regular,
            id: 751,
            cupSize: 16,
            price: 400,
            extrashot: [212],
            milk: [2011, 2111],
            numSyrup: 1,
            syrup: [2300, 2310, 2330],
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 100,
              bean2: 0,
              powder: 35,
              milk1: 63,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            id: 752,
            cupSize: 20,
            price: 420,
            extrashot: [212],
            milk: [2012, 2112],
            numSyrup: 1,
            syrup: [2301, 2311, 2331],
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 120,
              bean2: 0,
              powder: 44,
              milk1: 82,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hasChoco: true,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: true,
        hasIce: true,
        a_iBtnNbr: 9,
        img: 'MyAppCafe_Icons_Caffe Mocha Iced',
        category: ProductCategory.ice,
        baseId: 750,
      },
      '850': {
        name: 'Iced Chocolate',
        sizes: [
          {
            sizeName: SizeName.Regular,
            id: 851,
            cupSize: 16,
            price: 370,
            milk: [2011, 2111],
            numSyrup: 1,
            syrup: [2300, 2310, 2330],
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 0,
              bean2: 0,
              powder: 40,
              milk1: 82,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            id: 852,
            cupSize: 20,
            price: 400,
            milk: [2012, 2112],
            numSyrup: 1,
            syrup: [2301, 2311, 2331],
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 0,
              bean2: 0,
              powder: 50,
              milk1: 102,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hasChoco: true,
        hasMilk: true,
        hasExtrashot: false,
        hasSyrup: true,
        hasIce: true,
        a_iBtnNbr: 18,
        img: 'MyAppCafe_Icons_Iced Chocolate',
        category: ProductCategory.ice,
        baseId: 850,
      },
      '950': {
        name: 'Iced Americano',
        sizes: [
          {
            sizeName: SizeName.Regular,
            id: 951,
            cupSize: 16,
            price: 310,
            extrashot: [212],
            milk: [2010, 2011, 2111],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 130,
              bean2: 0,
              powder: 0,
              milk1: 0,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: false,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: false,
        hasIce: true,
        a_iBtnNbr: 22,
        special_a_iBtnNbr: [
          {
            a_iBtnNbr: 32,
            condition: [2011, 2012, 2111, 2112],
          },
        ],
        img: 'MyAppCafe_Icons_Americano Iced',
        category: ProductCategory.ice,
        baseId: 950,
      },
    },
    special: {
      '1000': {
        name: 'Caramel Macchiato',
        sizes: [
          {
            sizeName: SizeName.Small,
            id: 1001,
            cupSize: 12,
            price: 400,
            extrashot: [212],
            milk: [2011, 2111],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.S,
            recipe: {
              bean1: 120,
              bean2: 0,
              powder: 0,
              milk1: 128,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 1,
              cupXL: 0,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Regular,
            id: 1002,
            cupSize: 16,
            price: 450,
            extrashot: [212],
            milk: [2012, 2112],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 150,
              bean2: 0,
              powder: 0,
              milk1: 153,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            id: 1003,
            cupSize: 20,
            price: 500,
            extrashot: [212],
            milk: [2013, 2113],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 180,
              bean2: 0,
              powder: 0,
              milk1: 172,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hotColdSwitch: 1050,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: false,
        hasIce: false,
        a_iBtnNbr: 24,
        img: 'MyAppCafe_Icons_Caramel Macchiato',
        category: ProductCategory.special,
        baseId: 1000,
      },
      '1050': {
        name: 'Iced Caramel Macchiato',
        sizes: [
          {
            sizeName: SizeName.Regular,
            id: 1051,
            cupSize: 16,
            price: 450,
            extrashot: [212],
            milk: [2011, 2111],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 150,
              bean2: 0,
              powder: 0,
              milk1: 120,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            id: 1052,
            cupSize: 20,
            price: 500,
            extrashot: [212],
            milk: [2012, 2112],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 180,
              bean2: 0,
              powder: 0,
              milk1: 150,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hotColdSwitch: 1000,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: false,
        hasIce: true,
        a_iBtnNbr: 34,
        img: 'MyAppCafe_Icons_Caramel Macchiato',
        category: ProductCategory.special,
        baseId: 1050,
      },
      '1100': {
        name: 'Caramel Mocha',
        sizes: [
          {
            sizeName: SizeName.Small,
            builtInExtra: [2300],
            id: 1101,
            cupSize: 12,
            price: 400,
            extrashot: [212],
            milk: [2011, 2111],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.S,
            recipe: {
              bean1: 80,
              bean2: 0,
              powder: 26,
              milk1: 59,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 1,
              cupXL: 0,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Regular,
            builtInExtra: [2301],
            id: 1102,
            cupSize: 16,
            price: 450,
            extrashot: [212],
            milk: [2012, 2112],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 100,
              bean2: 0,
              powder: 35,
              milk1: 76,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            builtInExtra: [2302],
            id: 1103,
            cupSize: 20,
            price: 500,
            extrashot: [212],
            milk: [2013, 2113],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 120,
              bean2: 0,
              powder: 44,
              milk1: 93,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hotColdSwitch: 1150,
        hasChoco: true,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: false,
        hasIce: false,
        a_iBtnNbr: 15,
        img: 'MyAppCafe_Icons_Caramel Mocha',
        category: ProductCategory.special,
        baseId: 1100,
      },
      '1150': {
        name: 'Iced Caramel Mocha',
        sizes: [
          {
            sizeName: SizeName.Regular,
            builtInExtra: [2301],
            id: 1151,
            cupSize: 16,
            price: 450,
            extrashot: [212],
            milk: [2011, 2111],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 100,
              bean2: 0,
              powder: 35,
              milk1: 63,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            builtInExtra: [2302],
            id: 1152,
            cupSize: 20,
            price: 500,
            extrashot: [212],
            milk: [2012, 2112],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 120,
              bean2: 0,
              powder: 44,
              milk1: 82,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hotColdSwitch: 1100,
        hasChoco: true,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: false,
        hasIce: true,
        a_iBtnNbr: 9,
        img: 'MyAppCafe_Icons_Caramel Mocha',
        category: ProductCategory.special,
        baseId: 1150,
      },
      '1200': {
        name: 'Vanilla Chai',
        sizes: [
          {
            sizeName: SizeName.Small,
            id: 1201,
            cupSize: 12,
            price: 400,
            milk: [2011, 2111],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.S,
            recipe: {
              bean1: 0,
              bean2: 0,
              powder: 0,
              milk1: 217,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 1,
              cupXL: 0,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Regular,
            id: 1202,
            cupSize: 16,
            price: 450,
            milk: [2012, 2112],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 0,
              bean2: 0,
              powder: 0,
              milk1: 296,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            id: 1203,
            cupSize: 20,
            price: 500,
            milk: [2013, 2113],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 0,
              bean2: 0,
              powder: 0,
              milk1: 365,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hotColdSwitch: 1250,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: false,
        hasSyrup: false,
        hasIce: false,
        a_iBtnNbr: 25,
        img: 'MyAppCafe_Icons_Vanilla Chai',
        category: ProductCategory.special,
        baseId: 1200,
      },
      '1250': {
        name: 'Iced Vanilla Chai',
        sizes: [
          {
            sizeName: SizeName.Regular,
            id: 1251,
            cupSize: 16,
            price: 450,
            milk: [2011, 2111],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 0,
              bean2: 0,
              powder: 0,
              milk1: 215,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            id: 1252,
            cupSize: 20,
            price: 500,
            milk: [2012, 2112],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 0,
              bean2: 0,
              powder: 0,
              milk1: 348,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring, Season.Summer, Season.Autumn, Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hotColdSwitch: 1200,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: false,
        hasSyrup: false,
        hasIce: true,
        a_iBtnNbr: 35,
        img: 'MyAppCafe_Icons_Vanilla Chai',
        category: ProductCategory.special,
        baseId: 1250,
      },
      '1300': {
        name: 'Coconut Dream',
        sizes: [
          {
            sizeName: SizeName.Small,
            id: 1301,
            cupSize: 12,
            price: 400,
            extrashot: [212],
            milk: [2011, 2111],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.S,
            recipe: {
              bean1: 120,
              bean2: 0,
              powder: 0,
              milk1: 96,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 1,
              cupXL: 0,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Regular,
            id: 1302,
            cupSize: 16,
            price: 450,
            extrashot: [212],
            milk: [2012, 2112],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 150,
              bean2: 0,
              powder: 0,
              milk1: 129,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            id: 1303,
            cupSize: 20,
            price: 500,
            extrashot: [212],
            milk: [2013, 2113],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 180,
              bean2: 0,
              powder: 0,
              milk1: 154,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hotColdSwitch: 1350,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: false,
        hasIce: false,
        a_iBtnNbr: 26,
        img: 'MyAppCafe_Icons_Coconut Dream',
        category: ProductCategory.special,
        baseId: 1300,
      },
      '1350': {
        name: 'Iced Coconut Dream',
        sizes: [
          {
            sizeName: SizeName.Regular,
            id: 1351,
            cupSize: 16,
            price: 450,
            extrashot: [212],
            milk: [2011, 2111],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 150,
              bean2: 0,
              powder: 0,
              milk1: 107,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            id: 1352,
            cupSize: 20,
            price: 500,
            extrashot: [212],
            milk: [2012, 2112],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 180,
              bean2: 0,
              powder: 0,
              milk1: 150,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Spring],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hotColdSwitch: 1300,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: false,
        hasIce: true,
        a_iBtnNbr: 36,
        img: 'MyAppCafe_Icons_Coconut Dream',
        category: ProductCategory.special,
        baseId: 1350,
      },
      '1400': {
        name: 'Smores Latte',
        sizes: [
          {
            sizeName: SizeName.Small,
            builtInExtra: [2330],
            id: 1401,
            cupSize: 12,
            price: 400,
            extrashot: [212],
            milk: [2011, 2111],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.S,
            recipe: {
              bean1: 120,
              bean2: 0,
              powder: 0,
              milk1: 116,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 1,
              cupXL: 0,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Regular,
            builtInExtra: [2331],
            id: 1402,
            cupSize: 16,
            price: 450,
            extrashot: [212],
            milk: [2012, 2112],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 150,
              bean2: 0,
              powder: 0,
              milk1: 137,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            builtInExtra: [2332],
            id: 1403,
            cupSize: 20,
            price: 500,
            extrashot: [212],
            milk: [2013, 2113],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 180,
              bean2: 0,
              powder: 0,
              milk1: 170,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Summer],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hotColdSwitch: 1450,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: false,
        hasIce: false,
        a_iBtnNbr: 13,
        img: 'MyAppCafe_Icons_Smores Latte',
        category: ProductCategory.special,
        baseId: 1400,
      },
      '1450': {
        name: 'Iced Smores Latte',
        sizes: [
          {
            sizeName: SizeName.Regular,
            builtInExtra: [2331],
            id: 1451,
            cupSize: 16,
            price: 450,
            extrashot: [212],
            milk: [2011, 2111],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 150,
              bean2: 0,
              powder: 0,
              milk1: 120,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            builtInExtra: [2332],
            id: 1452,
            cupSize: 20,
            price: 500,
            extrashot: [212],
            milk: [2012, 2112],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 180,
              bean2: 0,
              powder: 0,
              milk1: 150,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Summer],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hotColdSwitch: 1400,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: false,
        hasIce: true,
        a_iBtnNbr: 17,
        img: 'MyAppCafe_Icons_Smores Latte',
        category: ProductCategory.special,
        baseId: 1450,
      },
      '1500': {
        name: 'Pumpkin Spice Latte',
        sizes: [
          {
            sizeName: SizeName.Small,
            builtInExtra: [2330],
            id: 1501,
            cupSize: 12,
            price: 400,
            extrashot: [212],
            milk: [2011, 2111],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.S,
            recipe: {
              bean1: 120,
              bean2: 0,
              powder: 0,
              milk1: 116,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 1,
              cupXL: 0,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Regular,
            builtInExtra: [2331],
            id: 1502,
            cupSize: 16,
            price: 450,
            extrashot: [212],
            milk: [2012, 2112],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 150,
              bean2: 0,
              powder: 0,
              milk1: 137,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            builtInExtra: [2332],
            id: 1503,
            cupSize: 20,
            price: 500,
            extrashot: [212],
            milk: [2013, 2113],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 180,
              bean2: 0,
              powder: 0,
              milk1: 170,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Autumn],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hotColdSwitch: 1550,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: false,
        hasIce: false,
        a_iBtnNbr: 13,
        img: 'MyAppCafe_Icons_Pumpkin Spice Latte',
        category: ProductCategory.special,
        baseId: 1500,
      },
      '1550': {
        name: 'Iced Pumpkin Spice Latte',
        sizes: [
          {
            sizeName: SizeName.Regular,
            builtInExtra: [2331],
            id: 1551,
            cupSize: 16,
            price: 450,
            extrashot: [212],
            milk: [2011, 2111],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 150,
              bean2: 0,
              powder: 0,
              milk1: 120,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            builtInExtra: [2332],
            id: 1552,
            cupSize: 20,
            price: 500,
            extrashot: [212],
            milk: [2012, 2112],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 180,
              bean2: 0,
              powder: 0,
              milk1: 150,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Autumn],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hotColdSwitch: 1500,
        hasChoco: false,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: false,
        hasIce: true,
        a_iBtnNbr: 17,
        img: 'MyAppCafe_Icons_Pumpkin Spice Latte',
        category: ProductCategory.special,
        baseId: 1550,
      },
      '1600': {
        name: 'Peppermint Mocha',
        sizes: [
          {
            sizeName: SizeName.Small,
            builtInExtra: [2330],
            id: 1601,
            cupSize: 12,
            price: 400,
            extrashot: [212],
            milk: [2011, 2111],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.S,
            recipe: {
              bean1: 0,
              bean2: 0,
              powder: 26,
              milk1: 59,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 1,
              cupXL: 0,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Regular,
            builtInExtra: [2331],
            id: 1602,
            cupSize: 16,
            price: 450,
            extrashot: [212],
            milk: [2012, 2112],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 0,
              bean2: 0,
              powder: 35,
              milk1: 76,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            builtInExtra: [2332],
            id: 1603,
            cupSize: 20,
            price: 500,
            extrashot: [212],
            milk: [2013, 2113],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 0,
              bean2: 0,
              powder: 44,
              milk1: 93,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hotColdSwitch: 1650,
        hasChoco: true,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: false,
        hasIce: false,
        a_iBtnNbr: 15,
        img: 'MyAppCafe_Icons_Peppermint Mocha',
        category: ProductCategory.special,
        baseId: 1600,
      },
      '1650': {
        name: 'Iced Peppermint Mocha',
        sizes: [
          {
            sizeName: SizeName.Regular,
            builtInExtra: [2331],
            id: 1651,
            cupSize: 16,
            price: 450,
            extrashot: [212],
            milk: [2011, 2111],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.M,
            recipe: {
              bean1: 0,
              bean2: 0,
              powder: 35,
              milk1: 63,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 1,
              cupXXL: 0,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
          {
            sizeName: SizeName.Grande,
            builtInExtra: [2332],
            id: 1652,
            cupSize: 20,
            price: 500,
            extrashot: [212],
            milk: [2012, 2112],
            numSyrup: 0,
            a_iSML: Coffeemachine_SML.L,
            recipe: {
              bean1: 0,
              bean2: 0,
              powder: 44,
              milk1: 82,
              milk2: 0,
              sugar: 1,
              lidM: 0,
              lidL: 1,
              cupM: 0,
              cupL: 0,
              cupXL: 0,
              cupXXL: 1,
              syrup1: 0,
              syrup2: 0,
              syrup3: 0,
              syrup4: 0,
              water: 0,
              franchiseTax: 20,
            },
          },
        ],
        season: [Season.Winter],
        isNamingSeasonal: false,
        isDisabled: false,
        hasPrint: true,
        hotColdSwitch: 1600,
        hasChoco: true,
        hasMilk: true,
        hasExtrashot: true,
        hasSyrup: false,
        hasIce: true,
        a_iBtnNbr: 9,
        img: 'MyAppCafe_Icons_Peppermint Mocha',
        category: ProductCategory.special,
        baseId: 1650,
      },
    },
  },
};
