import type { BoxConfig } from '../box';

export const sampleBoxConfig = {
  NotificationEmails: [],
  NotificationPhones: [],
  AutoBlinds: false,
  openingDate: '2032-10-15',
  name: 'MyAppCafé virtuelle Testbox',
  city: 'Karlsruhe',
  street: 'Schloßbezirk 10',
  zip: '76131',
  country: 'Deutschland',
  latitude: 49.01369068682524,
  longitude: 8.404399338707426,
  recipe: '2020-09-03',
  timeZone: 'Europe/Berlin',
  defaultLanguageShort: 'de',
  telegramChatIds: [],
  id: '55_7-zW9h5t',
  defaultLanguage: 'de-DE',
  languages: ['de', 'en'],
  times: {
    Monday: { start: '09:00:00', end: '20:00:00' },
    Tuesday: { start: '09:00:00', end: '20:00:00' },
    Wednesday: { start: '09:00:00', end: '20:00:00' },
    Thursday: { start: '09:00:00', end: '20:00:00' },
    Friday: { start: '09:00:00', end: '20:00:00' },
    Saturday: { start: '09:00:00', end: '20:00:00' },
    Sunday: { start: '09:00:00', end: '20:00:00' },
  },
  devices: [
    {
      $fulltype: 'MyAppCafeServer.Model.Robot',
      $type: 'Robot',
      $interfaces: [
        'IRobot',
        'ITcpClientDevice',
        'IConnectableDevice',
        'IDevice',
        'INotifyPropertyChanged',
        'IMaintainableDevice',
      ],
      Port: 49000,
      Side: 'Center',
      Nicename: 'Robot',
      SerialNumber: 'KAWASAKI',
      State: 'ShutDown',
      Hostname: '255.255.255.73',
      ProcessedJobsCount: 0,
      RemainingUnitsEstimate: 0,
      UnitsAfterRefill: 0,
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.CoffeeMachine_WMF9000s',
      $type: 'CoffeeMachine_WMF9000s',
      $interfaces: [
        'ICoffeeMachine',
        'IWebsocketDevice',
        'IConnectableDevice',
        'IDevice',
        'INotifyPropertyChanged',
        'IRefillableDevice',
        'IRestartableDevice',
        'ITrashableDevice',
        'IRobotAccessibleDevice',
      ],
      Port: 25000,
      Hostname: '255.255.255.73',
      Nicename: 'WMF links',
      SerialNumber: '12073',
      ProcessedJobsCount: 0,
      RemainingUnitsEstimate: 350,
      UnitsAfterRefill: 350,
      State: 'ShutDown',
      Side: 'L',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.CoffeeMachine_WMF9000s',
      $type: 'CoffeeMachine_WMF9000s',
      $interfaces: [
        'ICoffeeMachine',
        'IWebsocketDevice',
        'IConnectableDevice',
        'IDevice',
        'INotifyPropertyChanged',
        'IRefillableDevice',
        'IRestartableDevice',
        'ITrashableDevice',
        'IRobotAccessibleDevice',
      ],
      Port: 25000,
      Hostname: '255.255.255.74',
      Nicename: 'WMF rechts',
      SerialNumber: '12070',
      ProcessedJobsCount: 0,
      RemainingUnitsEstimate: 350,
      UnitsAfterRefill: 350,
      State: 'ShutDown',
      Side: 'R',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.RippleMakerMkII',
      $type: 'RippleMakerMkII',
      $interfaces: [
        'IPrinter',
        'IRobotAccessibleDevice',
        'IDevice',
        'INotifyPropertyChanged',
        'IRefillableDevice',
        'IConnectableDevice',
        'IHttpDevice',
        'ITrashableDevice',
        'IJobTimeoutDevice',
      ],
      SerialNumber: 'R2B1R00000000',
      Nicename: 'Ripplemaker rechts',
      Side: 'R',
      State: 'ShutDown',
      ProcessedJobsCount: 0,
      RemainingUnitsEstimate: 0,
      UnitsAfterRefill: 800,
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.RippleMakerMkII',
      $type: 'RippleMakerMkII',
      $interfaces: [
        'IPrinter',
        'IRobotAccessibleDevice',
        'IDevice',
        'INotifyPropertyChanged',
        'IRefillableDevice',
        'IConnectableDevice',
        'IHttpDevice',
        'ITrashableDevice',
        'IJobTimeoutDevice',
      ],
      SerialNumber: 'R2B1R00000001',
      Nicename: 'Ripplemaker links',
      Side: 'L',
      State: 'ShutDown',
      ProcessedJobsCount: 0,
      RemainingUnitsEstimate: 0,
      UnitsAfterRefill: 800,
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.PaymentTerminalDummy',
      $type: 'PaymentTerminalDummy',
      $interfaces: [
        'IPaymentTerminal',
        'IDevice',
        'INotifyPropertyChanged',
        'IMaintainableDevice',
        'IConnectableDevice',
        'IHttpDevice',
      ],
      Port: 8443,
      State: 'ShutDown',
      Side: 'L',
      Nicename: 'Kartenleser links',
      SerialNumber: 'P400Plus-XXXXXXX',
      Hostname: '255.255.255.25',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.PaymentTerminalDummy',
      $type: 'PaymentTerminalDummy',
      $interfaces: [
        'IPaymentTerminal',
        'IDevice',
        'INotifyPropertyChanged',
        'IMaintainableDevice',
        'IConnectableDevice',
        'IHttpDevice',
      ],
      Port: 8443,
      State: 'ShutDown',
      Side: 'R',
      Nicename: 'Kartenleser rechts',
      SerialNumber: 'P400Plus-YYYYYYY',
      Hostname: '255.255.255.26',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Gate',
      $type: 'Gate',
      $interfaces: [
        'IGate',
        'ITcpServerDevice',
        'IConnectableDevice',
        'IDevice',
        'INotifyPropertyChanged',
        'IRobotAccessibleDevice',
        'IMaintainableDevice',
        'IInitializingDevice',
      ],
      BeforeJobRobotPosition: 'Gate1',
      AfterJobRobotPosition: 'Gate1',
      Hostname: '255.255.255.21',
      Nicename: 'Gate 1',
      SerialNumber: 'RG312022040016',
      Side: 'L',
      Port: 50000,
      State: 'ShutDown',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Gate',
      $type: 'Gate',
      $interfaces: [
        'IGate',
        'ITcpServerDevice',
        'IConnectableDevice',
        'IDevice',
        'INotifyPropertyChanged',
        'IRobotAccessibleDevice',
        'IMaintainableDevice',
        'IInitializingDevice',
      ],
      Hostname: '255.255.255.22',
      Nicename: 'Gate 2',
      SerialNumber: 'RG312022060014',
      Side: 'L',
      Port: 50000,
      State: 'ShutDown',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Gate',
      $type: 'Gate',
      $interfaces: [
        'IGate',
        'ITcpServerDevice',
        'IConnectableDevice',
        'IDevice',
        'INotifyPropertyChanged',
        'IRobotAccessibleDevice',
        'IMaintainableDevice',
        'IInitializingDevice',
      ],
      Hostname: '255.255.255.23',
      Nicename: 'Gate 3',
      SerialNumber: 'RG312022060015',
      Side: 'R',
      Port: 50000,
      State: 'ShutDown',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.Scanner',
      $type: 'Scanner',
      $interfaces: [
        'IScanner',
        'IDevice',
        'INotifyPropertyChanged',
        'IUsbDevice',
        'IConnectableDevice',
        'IMaintainableDevice',
      ],
      Nicename: 'Scanner 1',
      SerialNumber: 'd727fcbb-7ed8-489a-af18-00abc2c4b308',
      Side: 'L',
      State: 'ShutDown',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.Scanner',
      $type: 'Scanner',
      $interfaces: [
        'IScanner',
        'IDevice',
        'INotifyPropertyChanged',
        'IUsbDevice',
        'IConnectableDevice',
        'IMaintainableDevice',
      ],
      Nicename: 'Scanner 2',
      SerialNumber: 'ad13c0e9-65fa-4a13-9deb-b78e2414914a',
      Side: 'R',
      State: 'ShutDown',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.DisplayDevice',
      $type: 'DisplayDevice',
      $interfaces: ['IDisplayDevice', 'IRestartableDevice', 'ISshDevice', 'IDevice', 'INotifyPropertyChanged'],
      SerialNumber: 'eacedc7d-7592-42ba-a847-638dfea6bef4',
      Nicename: 'Terminal left',
      Side: 'L',
      State: 'ShutDown',
      Hostname: '255.255.255.36',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.DisplayDevice',
      $type: 'DisplayDevice',
      $interfaces: ['IDisplayDevice', 'IRestartableDevice', 'ISshDevice', 'IDevice', 'INotifyPropertyChanged'],
      SerialNumber: 'eacedc7d-7592-42ba-a847-638dfea6bef4',
      Nicename: 'Terminal right',
      Side: 'L',
      State: 'ShutDown',
      Hostname: '255.255.255.37',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.CupHolder',
      $type: 'CupHolder',
      $interfaces: [],
      Side: 'L',
      Nicename: 'Cuptray left 8oz #1',
      SerialNumber: 'CupTrayLeft200_1',
      ProcessedJobsCount: 0,
      RemainingUnitsEstimate: 80,
      UnitsAfterRefill: 80,
      BeforeJobRobotPosition: 'CupTrayRight200_1',
      AfterJobRobotPosition: 'CupTrayRight200_1',
      State: 'ShutDown',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.CupHolder',
      $type: 'CupHolder',
      $interfaces: [],
      Side: 'R',
      Nicename: 'Cuptray right 8oz #1',
      SerialNumber: 'CupTrayRight200_1',
      ProcessedJobsCount: 0,
      RemainingUnitsEstimate: 80,
      UnitsAfterRefill: 80,
      IsAlwaysRefilledOnMaintenance: true,
      BeforeJobRobotPosition: 'CupTrayRight200_1',
      AfterJobRobotPosition: 'CupTrayRight200_1',
      State: 'Available',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.CupHolder',
      $type: 'CupHolder',
      $interfaces: [],
      Side: 'L',
      Nicename: 'Cuptray left 12oz #1',
      SerialNumber: 'CupTrayLeft300_1',
      ProcessedJobsCount: 0,
      RemainingUnitsEstimate: 50,
      UnitsAfterRefill: 50,
      IsAlwaysRefilledOnMaintenance: true,
      BeforeJobRobotPosition: 'CupTrayLeft300_1',
      AfterJobRobotPosition: 'CupTrayLeft300_1',
      State: 'ProcessingJob',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.CupHolder',
      $type: 'CupHolder',
      $interfaces: [],
      Side: 'R',
      Nicename: 'Cuptray right 12oz #1',
      SerialNumber: 'CupTrayRight300_1',
      ProcessedJobsCount: 0,
      RemainingUnitsEstimate: 50,
      UnitsAfterRefill: 50,
      IsAlwaysRefilledOnMaintenance: true,
      BeforeJobRobotPosition: 'CupTrayRight300_1',
      AfterJobRobotPosition: 'CupTrayRight300_1',
      State: 'ShutDown',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.CupHolder',
      $type: 'CupHolder',
      $interfaces: [],
      Side: 'L',
      Nicename: 'Cuptray left 12oz #2',
      SerialNumber: 'CupTrayLeft300_2',
      ProcessedJobsCount: 0,
      RemainingUnitsEstimate: 50,
      UnitsAfterRefill: 50,
      IsAlwaysRefilledOnMaintenance: true,
      BeforeJobRobotPosition: 'CupTrayLeft300_2',
      AfterJobRobotPosition: 'CupTrayLeft300_2',
      State: 'ShutDown',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.CupHolder',
      $type: 'CupHolder',
      $interfaces: [],
      Side: 'R',
      Nicename: 'Cuptray right 12oz #2',
      SerialNumber: 'CupTrayRight300_2',
      ProcessedJobsCount: 0,
      RemainingUnitsEstimate: 50,
      UnitsAfterRefill: 50,
      IsAlwaysRefilledOnMaintenance: true,
      BeforeJobRobotPosition: 'CupTrayRight300_2',
      AfterJobRobotPosition: 'CupTrayRight300_2',
      State: 'Maintenance',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.CupHolder',
      $type: 'CupHolder',
      $interfaces: [],
      Side: 'L',
      Nicename: 'Cuptray left 16oz #1',
      SerialNumber: 'CupTrayLeft400_1',
      ProcessedJobsCount: 0,
      RemainingUnitsEstimate: 50,
      UnitsAfterRefill: 50,
      IsAlwaysRefilledOnMaintenance: true,
      BeforeJobRobotPosition: 'CupTrayLeft400_1',
      AfterJobRobotPosition: 'CupTrayLeft400_1',
      State: 'ShutDown',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.CupHolder',
      $type: 'CupHolder',
      $interfaces: [],
      Side: 'R',
      Nicename: 'Cuptray right 16oz #1',
      SerialNumber: 'CupTrayRight400_1',
      ProcessedJobsCount: 0,
      RemainingUnitsEstimate: 50,
      UnitsAfterRefill: 50,
      IsAlwaysRefilledOnMaintenance: true,
      BeforeJobRobotPosition: 'CupTrayRight400_1',
      AfterJobRobotPosition: 'CupTrayRight400_1',
      State: 'JobDone',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.CupHolder',
      $type: 'CupHolder',
      $interfaces: [],
      Side: 'L',
      Nicename: 'Cuptray left 16oz #2',
      SerialNumber: 'CupTrayLeft400_2',
      ProcessedJobsCount: 0,
      RemainingUnitsEstimate: 50,
      UnitsAfterRefill: 50,
      IsAlwaysRefilledOnMaintenance: true,
      BeforeJobRobotPosition: 'CupTrayLeft400_2',
      AfterJobRobotPosition: 'CupTrayLeft400_2',
      State: 'ShutDown',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.CupHolder',
      $type: 'CupHolder',
      $interfaces: [],
      Side: 'R',
      Nicename: 'Cuptray right 16oz #2',
      SerialNumber: 'CupTrayRight400_2',
      ProcessedJobsCount: 0,
      RemainingUnitsEstimate: 50,
      UnitsAfterRefill: 50,
      IsAlwaysRefilledOnMaintenance: true,
      BeforeJobRobotPosition: 'CupTrayRight400_2',
      AfterJobRobotPosition: 'CupTrayRight400_2',
      State: 'Error',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.CupHolder',
      $type: 'CupHolder',
      $interfaces: [],
      Side: 'L',
      Nicename: 'Cuptray left 20oz #1',
      SerialNumber: 'CupTrayLeft500_1',
      ProcessedJobsCount: 0,
      RemainingUnitsEstimate: 50,
      UnitsAfterRefill: 50,
      IsAlwaysRefilledOnMaintenance: true,
      BeforeJobRobotPosition: 'CupTrayLeft500_1',
      AfterJobRobotPosition: 'CupTrayLeft500_1',
      State: 'Available',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.CupHolder',
      $type: 'CupHolder',
      $interfaces: [],
      Side: 'R',
      Nicename: 'Cuptray right 20oz #1',
      SerialNumber: 'CupTrayRight500_1',
      ProcessedJobsCount: 0,
      RemainingUnitsEstimate: 50,
      UnitsAfterRefill: 50,
      IsAlwaysRefilledOnMaintenance: true,
      BeforeJobRobotPosition: 'CupTrayRight500_1',
      AfterJobRobotPosition: 'CupTrayRight500_1',
      State: 'Disabled',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.CupHolder',
      $type: 'CupHolder',
      $interfaces: [],
      Side: 'L',
      Nicename: 'Cuptray left 20oz #2',
      SerialNumber: 'CupTrayLeft500_2',
      ProcessedJobsCount: 0,
      RemainingUnitsEstimate: 50,
      UnitsAfterRefill: 50,
      IsAlwaysRefilledOnMaintenance: true,
      BeforeJobRobotPosition: 'CupTrayLeft500_2',
      AfterJobRobotPosition: 'CupTrayLeft500_2',
      State: 'ShutDown',
    },
    {
      $fulltype: 'MyAppCafeServer.Model.Devices.CupHolder',
      $type: 'CupHolder',
      $interfaces: [],
      Side: 'R',
      Nicename: 'Cuptray right 20oz #2',
      SerialNumber: 'CupTrayRight500_2',
      ProcessedJobsCount: 0,
      RemainingUnitsEstimate: 50,
      UnitsAfterRefill: 50,
      IsAlwaysRefilledOnMaintenance: true,
      BeforeJobRobotPosition: 'CupTrayRight500_2',
      AfterJobRobotPosition: 'CupTrayRight500_2',
      State: 'ShutDown',
    },
  ],
  tax: {
    name: 'MyAppCafé virtuelle Testbox',
    number: 'DEXXXXXXXXXX',
    zip: '76131',
    city: 'Karlsruhe',
    street: 'Schloßbezirk 10',
    country: 'Deutschland',
    rate: 0.19,
    merchantIdPOS: '',
    merchantIdECOM: '',
    currency: 'EUR',
    receiptPrefix: 'A-',
  },
} satisfies BoxConfig;
